name: Test Python package

on: 
  push: {}
  pull_request: {}
  schedule: [cron: '0 12 * * 3'] # every Wednesday at noon

jobs:
  build:
    
    strategy:
      matrix:
        python: ['3.8', '3.11']
        java: [13]
        os: ['ubuntu-latest'] # 
        architecture: ['x64']
        terrier: ['snapshot'] #'5.3', '5.4-SNAPSHOT', 

    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@v4

    - name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        architecture: ${{ matrix.architecture }}

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        python-version: ${{ matrix.python }}
        conda-channels: anaconda, conda-forge
        activate-conda: true

    - name: Install Python dependencies
      run: |
        conda install pip
        pip install -r requirements.txt
        # install this software
        pip install --timeout=120 .
        pip install pytest
        conda list
        
    - name: All unit tests
      env:
        TERRIER_VERSION: ${{ matrix.terrier }}
      run: |
        pytest -s -p no:faulthandler
