name: style

on:
  push: {branches: [master]} # pushes to master
  pull_request: {} # all PRs

jobs:
  ruff:
    strategy:
      matrix:
        python-version: ['3.10']
        os: ['ubuntu-latest']

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Dependencies
      uses: actions/cache@v4
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ matrix.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements.txt', 'requirements-dev.txt') }}

    - name: Install Dependencies
      run: |
        pip install --upgrade -r requirements-dev.txt
        pip install -e .

    - name: Ruff
      run: 'ruff check --output-format=github pyterrier_doc2query'
